/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AccountStatus {
  account_id?: string;
  account_name?: string;
  balance?: number;

  /**
   * False if the sum of all transaction legs for this account is inconsistent
   */
  is_balanced?: boolean;
  warnings?: Array<string>;
}
