/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ErrorResponse {

  /**
   * A human-readable explanation specific to this occurence.
   */
  detail?: string;

  /**
   * A URI reference for this specific occurence (e.g. trace ID)
   */
  instance?: string;

  /**
   * The HTTP status code generated for this occurrence.
   */
  status: string;

  /**
   * A short, human-readable summary of the problem
   */
  title: string;

  /**
   * A URI reference that identifies the problem type.
   */
  type: string;
}
