/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Double-entry accounting ledger posting (journal entry)
 */
export interface Posting {
  description: string;
  id: string;
  system_notes: string;
  transacted_at: string;
}
