/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Double-entry accounting entry - debit / credit
 */
export interface TransactionEntry {

  /**
   * ...
   */
  credit_amount: string;

  /**
   * ...
   */
  debit_amount: string;

  /**
   * transaction id
   */
  transaction_id: string;
}
