/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Entry } from '../models/entry';

/**
 * Double-entry accounting transaction
 */
export interface Transaction {
  date: string;
  description: string;
  entries: Array<Entry>;
  id?: string;
}
