// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: entries.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEntry = `-- name: CreateEntry :one
INSERT INTO entries (
  description
  , system_notes
  , postings_id
  , ledger_accounts_id
  , debit_microsgd
  , credit_microsgd
) VALUES (
  $1, $2, $3, $4, $5, $6
)
RETURNING id, description, system_notes, postings_id, ledger_accounts_id, debit_microsgd, credit_microsgd
`

type CreateEntryParams struct {
	Description      pgtype.Text `json:"description"`
	SystemNotes      pgtype.Text `json:"system_notes"`
	PostingsID       int64       `json:"postings_id"`
	LedgerAccountsID int64       `json:"ledger_accounts_id"`
	DebitMicrosgd    int64       `json:"debit_microsgd"`
	CreditMicrosgd   int64       `json:"credit_microsgd"`
}

func (q *Queries) CreateEntry(ctx context.Context, arg CreateEntryParams) (Entry, error) {
	row := q.db.QueryRow(ctx, createEntry,
		arg.Description,
		arg.SystemNotes,
		arg.PostingsID,
		arg.LedgerAccountsID,
		arg.DebitMicrosgd,
		arg.CreditMicrosgd,
	)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.Description,
		&i.SystemNotes,
		&i.PostingsID,
		&i.LedgerAccountsID,
		&i.DebitMicrosgd,
		&i.CreditMicrosgd,
	)
	return i, err
}

const deleteEntry = `-- name: DeleteEntry :exec
DELETE FROM entries
WHERE id = $1
`

func (q *Queries) DeleteEntry(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteEntry, id)
	return err
}

const getEntry = `-- name: GetEntry :one
SELECT id, description, system_notes, postings_id, ledger_accounts_id, debit_microsgd, credit_microsgd
FROM entries
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetEntry(ctx context.Context, id int64) (Entry, error) {
	row := q.db.QueryRow(ctx, getEntry, id)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.Description,
		&i.SystemNotes,
		&i.PostingsID,
		&i.LedgerAccountsID,
		&i.DebitMicrosgd,
		&i.CreditMicrosgd,
	)
	return i, err
}

const listEntries = `-- name: ListEntries :many
SELECT id, description, system_notes, postings_id, ledger_accounts_id, debit_microsgd, credit_microsgd
FROM entries
`

func (q *Queries) ListEntries(ctx context.Context) ([]Entry, error) {
	rows, err := q.db.Query(ctx, listEntries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Entry
	for rows.Next() {
		var i Entry
		if err := rows.Scan(
			&i.ID,
			&i.Description,
			&i.SystemNotes,
			&i.PostingsID,
			&i.LedgerAccountsID,
			&i.DebitMicrosgd,
			&i.CreditMicrosgd,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEntry = `-- name: UpdateEntry :one
UPDATE entries
SET
  description = $2
  , system_notes = $3
  , ledger_accounts_id = $4
  , debit_microsgd = $5
  , credit_microsgd = $6
WHERE id = $1
RETURNING id, description, system_notes, postings_id, ledger_accounts_id, debit_microsgd, credit_microsgd
`

type UpdateEntryParams struct {
	ID               int64       `json:"id"`
	Description      pgtype.Text `json:"description"`
	SystemNotes      pgtype.Text `json:"system_notes"`
	LedgerAccountsID int64       `json:"ledger_accounts_id"`
	DebitMicrosgd    int64       `json:"debit_microsgd"`
	CreditMicrosgd   int64       `json:"credit_microsgd"`
}

func (q *Queries) UpdateEntry(ctx context.Context, arg UpdateEntryParams) (Entry, error) {
	row := q.db.QueryRow(ctx, updateEntry,
		arg.ID,
		arg.Description,
		arg.SystemNotes,
		arg.LedgerAccountsID,
		arg.DebitMicrosgd,
		arg.CreditMicrosgd,
	)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.Description,
		&i.SystemNotes,
		&i.PostingsID,
		&i.LedgerAccountsID,
		&i.DebitMicrosgd,
		&i.CreditMicrosgd,
	)
	return i, err
}
