// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ledger_accounts.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createLedgerAccount = `-- name: CreateLedgerAccount :one
INSERT INTO ledger_accounts (
  name,
  description,
  parent_id
) VALUES (
  $1, $2, $3
)
RETURNING id, name, description, parent_id
`

type CreateLedgerAccountParams struct {
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	ParentID    pgtype.Int8 `json:"parent_id"`
}

func (q *Queries) CreateLedgerAccount(ctx context.Context, arg CreateLedgerAccountParams) (LedgerAccount, error) {
	row := q.db.QueryRow(ctx, createLedgerAccount, arg.Name, arg.Description, arg.ParentID)
	var i LedgerAccount
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ParentID,
	)
	return i, err
}

const deleteLedgerAccount = `-- name: DeleteLedgerAccount :exec
DELETE FROM ledger_accounts
WHERE id = $1
`

func (q *Queries) DeleteLedgerAccount(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteLedgerAccount, id)
	return err
}

const getLedgerAccount = `-- name: GetLedgerAccount :one
SELECT id, name, description, parent_id 
FROM ledger_accounts
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetLedgerAccount(ctx context.Context, id int64) (LedgerAccount, error) {
	row := q.db.QueryRow(ctx, getLedgerAccount, id)
	var i LedgerAccount
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ParentID,
	)
	return i, err
}

const listLedgerAccounts = `-- name: ListLedgerAccounts :many
WITH RECURSIVE account_tree AS (
    -- Base Case: Select root accounts
    SELECT 
        id,
        name,
        description,
        parent_id,
        name::TEXT AS qualified_name,
        1 AS level
    FROM ledger_accounts
    WHERE parent_id IS NULL

    UNION ALL

    -- Recursive Step: Join children to parents
    SELECT 
        child.id,
        child.name,
        child.description,
        child.parent_id,
        (parent.qualified_name || ':' || child.name)::TEXT AS qualified_name,
        parent.level + 1 AS level
    FROM ledger_accounts child
    JOIN account_tree parent ON child.parent_id = parent.id
)
SELECT id, name, qualified_name, description, parent_id, level
FROM account_tree 
ORDER BY qualified_name
`

type ListLedgerAccountsRow struct {
	ID            int64       `json:"id"`
	Name          string      `json:"name"`
	QualifiedName string      `json:"qualified_name"`
	Description   pgtype.Text `json:"description"`
	ParentID      pgtype.Int8 `json:"parent_id"`
	Level         int32       `json:"level"`
}

func (q *Queries) ListLedgerAccounts(ctx context.Context) ([]ListLedgerAccountsRow, error) {
	rows, err := q.db.Query(ctx, listLedgerAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLedgerAccountsRow
	for rows.Next() {
		var i ListLedgerAccountsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.QualifiedName,
			&i.Description,
			&i.ParentID,
			&i.Level,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLedgerAccount = `-- name: UpdateLedgerAccount :one
UPDATE ledger_accounts
SET
  name = $2,
  description = $3,
  parent_id = $4
WHERE id = $1
RETURNING id, name, description, parent_id
`

type UpdateLedgerAccountParams struct {
	ID          int64       `json:"id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	ParentID    pgtype.Int8 `json:"parent_id"`
}

func (q *Queries) UpdateLedgerAccount(ctx context.Context, arg UpdateLedgerAccountParams) (LedgerAccount, error) {
	row := q.db.QueryRow(ctx, updateLedgerAccount,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.ParentID,
	)
	var i LedgerAccount
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ParentID,
	)
	return i, err
}
