// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: postings.sql

package dbgen

import (
	"context"
)

const getPostingsList = `-- name: GetPostingsList :many
SELECT id, description, system_notes, transacted_at
FROM postings
`

func (q *Queries) GetPostingsList(ctx context.Context) ([]Posting, error) {
	rows, err := q.db.Query(ctx, getPostingsList)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Posting
	for rows.Next() {
		var i Posting
		if err := rows.Scan(
			&i.ID,
			&i.Description,
			&i.SystemNotes,
			&i.TransactedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
