-- +goose Up
-- +goose StatementBegin
CREATE TABLE IF NOT EXISTS ledger_accounts (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
  , name        VARCHAR(255) NOT NULL
  , description TEXT
  , parent_id   BIGINT REFERENCES ledger_accounts (id) DEFAULT NULL
);

COMMENT ON TABLE ledger_accounts IS 'The Chart of Accounts (COA). Defines the categories where value is moved.';
COMMENT ON COLUMN ledger_accounts.id IS 'Primary key for the account.';
COMMENT ON COLUMN ledger_accounts.name IS 'The human-friendly name of the account (e.g., Cash at Bank, Accounts Payable).';
COMMENT ON COLUMN ledger_accounts.description IS 'Detailed definition of what should be recorded in this account.';
COMMENT ON COLUMN ledger_accounts.parent_id IS 'Self-reference to create an account hierarchy (e.g., Assets > Current Assets).';


CREATE TABLE IF NOT EXISTS postings (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
  , description   TEXT
  , system_notes  TEXT
  , transacted_at TIMESTAMPTZ NOT NULL
);

COMMENT ON TABLE postings IS 'The Header/Journal Entry level. Groups multiple entries into a single balanced transaction.';
COMMENT ON COLUMN postings.id IS 'Primary key for the transaction group.';
COMMENT ON COLUMN postings.description IS 'The narrative description of the transaction for human review.';
COMMENT ON COLUMN postings.system_notes IS 'Technical metadata, source system IDs, or debugging info (e.g., source: asdf.csv).';
COMMENT ON COLUMN postings.transacted_at IS 'The effective date and time the financial event occurred.';


CREATE TABLE IF NOT EXISTS entries (
  id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
  , description        TEXT
  , system_notes       TEXT
  , postings_id        BIGINT REFERENCES postings(id) NOT NULL
  , ledger_accounts_id BIGINT REFERENCES ledger_accounts (id) NOT NULL
  , debit_microsgd     BIGINT NOT NULL
  , credit_microsgd    BIGINT NOT NULL
);

COMMENT ON TABLE entries IS 'The atomic line items of a transaction. The sum of debits must equal the sum of credits for a given posting_id.';
COMMENT ON COLUMN entries.id IS 'Primary key for the individual line item.';
COMMENT ON COLUMN entries.description IS 'Specific line-item memo, if different from the main posting description.';
COMMENT ON COLUMN entries.system_notes IS 'Technical details specific to this leg of the transaction.';
COMMENT ON COLUMN entries.postings_id IS 'Foreign key linking this entry to its parent transaction.';
COMMENT ON COLUMN entries.ledger_accounts_id IS 'The specific account from the COA (chart of accounts; ledger_accounts table) being impacted.';
COMMENT ON COLUMN entries.debit_microsgd IS 'The value increase/decrease (base integer) on the debit side. 1 SGD = 1,000,000 mSGD';
COMMENT ON COLUMN entries.credit_microsgd IS 'The value increase/decrease (base integer) on the credit side. 1 SGD = 1,000,000 mSGD';
-- +goose StatementEnd
