/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { AccountBalanceNode } from '../models/account-balance-node';
import { apiV1AccountingLedgerAccountsGet } from '../fn/accounting/api-v-1-accounting-ledger-accounts-get';
import { ApiV1AccountingLedgerAccountsGet$Params } from '../fn/accounting/api-v-1-accounting-ledger-accounts-get';
import { apiV1AccountingPostingsGet } from '../fn/accounting/api-v-1-accounting-postings-get';
import { ApiV1AccountingPostingsGet$Params } from '../fn/accounting/api-v-1-accounting-postings-get';
import { createEntry } from '../fn/accounting/create-entry';
import { CreateEntry$Params } from '../fn/accounting/create-entry';
import { deleteEntry } from '../fn/accounting/delete-entry';
import { DeleteEntry$Params } from '../fn/accounting/delete-entry';
import { Entry } from '../models/entry';
import { getAccountBalances } from '../fn/accounting/get-account-balances';
import { GetAccountBalances$Params } from '../fn/accounting/get-account-balances';
import { getEntries } from '../fn/accounting/get-entries';
import { GetEntries$Params } from '../fn/accounting/get-entries';
import { LedgerAccount } from '../models/ledger-account';
import { Posting } from '../models/posting';
import { updateEntry } from '../fn/accounting/update-entry';
import { UpdateEntry$Params } from '../fn/accounting/update-entry';

@Injectable({ providedIn: 'root' })
export class AccountingService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiV1AccountingLedgerAccountsGet()` */
  static readonly ApiV1AccountingLedgerAccountsGetPath = '/api/v1/accounting/ledger_accounts';

  /**
   * List all ledger accounts.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiV1AccountingLedgerAccountsGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiV1AccountingLedgerAccountsGet$Response(params?: ApiV1AccountingLedgerAccountsGet$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'data'?: Array<LedgerAccount>;
}>> {
    const obs = apiV1AccountingLedgerAccountsGet(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * List all ledger accounts.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiV1AccountingLedgerAccountsGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiV1AccountingLedgerAccountsGet(params?: ApiV1AccountingLedgerAccountsGet$Params, context?: HttpContext): Observable<{
'data'?: Array<LedgerAccount>;
}> {
    const resp = this.apiV1AccountingLedgerAccountsGet$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<{
'data'?: Array<LedgerAccount>;
}>): {
'data'?: Array<LedgerAccount>;
} => r.body)
    );
  }

  /** Path part for operation `apiV1AccountingPostingsGet()` */
  static readonly ApiV1AccountingPostingsGetPath = '/api/v1/accounting/postings';

  /**
   * List all postings.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiV1AccountingPostingsGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiV1AccountingPostingsGet$Response(params?: ApiV1AccountingPostingsGet$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'data'?: Array<Posting>;
}>> {
    const obs = apiV1AccountingPostingsGet(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * List all postings.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiV1AccountingPostingsGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiV1AccountingPostingsGet(params?: ApiV1AccountingPostingsGet$Params, context?: HttpContext): Observable<{
'data'?: Array<Posting>;
}> {
    const resp = this.apiV1AccountingPostingsGet$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<{
'data'?: Array<Posting>;
}>): {
'data'?: Array<Posting>;
} => r.body)
    );
  }

  /** Path part for operation `getEntries()` */
  static readonly GetEntriesPath = '/api/v1/accounting/entries';

  /**
   * List all entries.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getEntries()` instead.
   *
   * This method doesn't expect any request body.
   */
  getEntries$Response(params?: GetEntries$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'data'?: Array<Entry>;
}>> {
    const obs = getEntries(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * List all entries.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getEntries$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getEntries(params?: GetEntries$Params, context?: HttpContext): Observable<{
'data'?: Array<Entry>;
}> {
    const resp = this.getEntries$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<{
'data'?: Array<Entry>;
}>): {
'data'?: Array<Entry>;
} => r.body)
    );
  }

  /** Path part for operation `createEntry()` */
  static readonly CreateEntryPath = '/api/v1/accounting/entries';

  /**
   * create entry.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createEntry()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createEntry$Response(params: CreateEntry$Params, context?: HttpContext): Observable<StrictHttpResponse<Entry>> {
    const obs = createEntry(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * create entry.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createEntry$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createEntry(params: CreateEntry$Params, context?: HttpContext): Observable<Entry> {
    const resp = this.createEntry$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Entry>): Entry => r.body)
    );
  }

  /** Path part for operation `updateEntry()` */
  static readonly UpdateEntryPath = '/api/v1/accounting/entries/{entry_id}';

  /**
   * replace of a ledger entry.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateEntry()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateEntry$Response(params: UpdateEntry$Params, context?: HttpContext): Observable<StrictHttpResponse<{
}>> {
    const obs = updateEntry(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * replace of a ledger entry.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateEntry$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateEntry(params: UpdateEntry$Params, context?: HttpContext): Observable<{
}> {
    const resp = this.updateEntry$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<{
}>): {
} => r.body)
    );
  }

  /** Path part for operation `deleteEntry()` */
  static readonly DeleteEntryPath = '/api/v1/accounting/entries/{entry_id}';

  /**
   * delete ledger entry.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteEntry()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteEntry$Response(params: DeleteEntry$Params, context?: HttpContext): Observable<StrictHttpResponse<{
}>> {
    const obs = deleteEntry(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * delete ledger entry.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteEntry$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteEntry(params: DeleteEntry$Params, context?: HttpContext): Observable<{
}> {
    const resp = this.deleteEntry$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<{
}>): {
} => r.body)
    );
  }

  /** Path part for operation `getAccountBalances()` */
  static readonly GetAccountBalancesPath = '/api/v1/accounting/reports/account_balances';

  /**
   * Get account balances and tree roll-ups for a date range.
   *
   * Returns the full chart of accounts with individual and aggregated (rolled-up) debit/credit totals for the specified period.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAccountBalances()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAccountBalances$Response(params: GetAccountBalances$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'data'?: Array<AccountBalanceNode>;
}>> {
    const obs = getAccountBalances(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Get account balances and tree roll-ups for a date range.
   *
   * Returns the full chart of accounts with individual and aggregated (rolled-up) debit/credit totals for the specified period.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAccountBalances$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAccountBalances(params: GetAccountBalances$Params, context?: HttpContext): Observable<{
'data'?: Array<AccountBalanceNode>;
}> {
    const resp = this.getAccountBalances$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<{
'data'?: Array<AccountBalanceNode>;
}>): {
'data'?: Array<AccountBalanceNode>;
} => r.body)
    );
  }

}
