/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { AccountStatus } from '../models/account-status';
import { apiV1AccountingAccountsInfoGet } from '../fn/accounting/api-v-1-accounting-accounts-info-get';
import { ApiV1AccountingAccountsInfoGet$Params } from '../fn/accounting/api-v-1-accounting-accounts-info-get';
import { apiV1AccountingTransactionsGet } from '../fn/accounting/api-v-1-accounting-transactions-get';
import { ApiV1AccountingTransactionsGet$Params } from '../fn/accounting/api-v-1-accounting-transactions-get';
import { apiV1AccountingTransactionsPost } from '../fn/accounting/api-v-1-accounting-transactions-post';
import { ApiV1AccountingTransactionsPost$Params } from '../fn/accounting/api-v-1-accounting-transactions-post';
import { apiV1AccountingTransactionsTransactionIdPut } from '../fn/accounting/api-v-1-accounting-transactions-transaction-id-put';
import { ApiV1AccountingTransactionsTransactionIdPut$Params } from '../fn/accounting/api-v-1-accounting-transactions-transaction-id-put';
import { Transaction } from '../models/transaction';

@Injectable({ providedIn: 'root' })
export class AccountingService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiV1AccountingTransactionsGet()` */
  static readonly ApiV1AccountingTransactionsGetPath = '/api/v1/accounting/transactions';

  /**
   * List all transactions.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiV1AccountingTransactionsGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiV1AccountingTransactionsGet$Response(params?: ApiV1AccountingTransactionsGet$Params, context?: HttpContext): Promise<StrictHttpResponse<{
'data'?: Array<Transaction>;
}>> {
    const obs = apiV1AccountingTransactionsGet(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * List all transactions.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiV1AccountingTransactionsGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiV1AccountingTransactionsGet(params?: ApiV1AccountingTransactionsGet$Params, context?: HttpContext): Promise<{
'data'?: Array<Transaction>;
}> {
    const resp = this.apiV1AccountingTransactionsGet$Response(params, context);
    return resp.then((r: StrictHttpResponse<{
'data'?: Array<Transaction>;
}>): {
'data'?: Array<Transaction>;
} => r.body);
  }

  /** Path part for operation `apiV1AccountingTransactionsPost()` */
  static readonly ApiV1AccountingTransactionsPostPath = '/api/v1/accounting/transactions';

  /**
   * Create transaction.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiV1AccountingTransactionsPost()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiV1AccountingTransactionsPost$Response(params?: ApiV1AccountingTransactionsPost$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = apiV1AccountingTransactionsPost(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Create transaction.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiV1AccountingTransactionsPost$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiV1AccountingTransactionsPost(params?: ApiV1AccountingTransactionsPost$Params, context?: HttpContext): Promise<void> {
    const resp = this.apiV1AccountingTransactionsPost$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

  /** Path part for operation `apiV1AccountingTransactionsTransactionIdPut()` */
  static readonly ApiV1AccountingTransactionsTransactionIdPutPath = '/api/v1/accounting/transactions/{transaction_id}';

  /**
   * Update or finalize a generated transaction.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiV1AccountingTransactionsTransactionIdPut()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  apiV1AccountingTransactionsTransactionIdPut$Response(params: ApiV1AccountingTransactionsTransactionIdPut$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = apiV1AccountingTransactionsTransactionIdPut(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Update or finalize a generated transaction.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiV1AccountingTransactionsTransactionIdPut$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  apiV1AccountingTransactionsTransactionIdPut(params: ApiV1AccountingTransactionsTransactionIdPut$Params, context?: HttpContext): Promise<void> {
    const resp = this.apiV1AccountingTransactionsTransactionIdPut$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

  /** Path part for operation `apiV1AccountingAccountsInfoGet()` */
  static readonly ApiV1AccountingAccountsInfoGetPath = '/api/v1/accounting/accounts/info';

  /**
   * Balance and health check.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiV1AccountingAccountsInfoGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiV1AccountingAccountsInfoGet$Response(params?: ApiV1AccountingAccountsInfoGet$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<AccountStatus>>> {
    const obs = apiV1AccountingAccountsInfoGet(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Balance and health check.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiV1AccountingAccountsInfoGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiV1AccountingAccountsInfoGet(params?: ApiV1AccountingAccountsInfoGet$Params, context?: HttpContext): Promise<Array<AccountStatus>> {
    const resp = this.apiV1AccountingAccountsInfoGet$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<AccountStatus>>): Array<AccountStatus> => r.body);
  }

}
