/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { AccountStatus } from '../models/account-status';
import { apiV1AccountingAccountsInfoGet } from '../fn/accounting/api-v-1-accounting-accounts-info-get';
import { ApiV1AccountingAccountsInfoGet$Params } from '../fn/accounting/api-v-1-accounting-accounts-info-get';
import { apiV1AccountingEntriesGet } from '../fn/accounting/api-v-1-accounting-entries-get';
import { ApiV1AccountingEntriesGet$Params } from '../fn/accounting/api-v-1-accounting-entries-get';
import { apiV1AccountingLedgerAccountsGet } from '../fn/accounting/api-v-1-accounting-ledger-accounts-get';
import { ApiV1AccountingLedgerAccountsGet$Params } from '../fn/accounting/api-v-1-accounting-ledger-accounts-get';
import { apiV1AccountingPostingsGet } from '../fn/accounting/api-v-1-accounting-postings-get';
import { ApiV1AccountingPostingsGet$Params } from '../fn/accounting/api-v-1-accounting-postings-get';
import { apiV1AccountingTransactionsGet } from '../fn/accounting/api-v-1-accounting-transactions-get';
import { ApiV1AccountingTransactionsGet$Params } from '../fn/accounting/api-v-1-accounting-transactions-get';
import { apiV1AccountingTransactionsPost } from '../fn/accounting/api-v-1-accounting-transactions-post';
import { ApiV1AccountingTransactionsPost$Params } from '../fn/accounting/api-v-1-accounting-transactions-post';
import { apiV1AccountingTransactionsTransactionIdPut } from '../fn/accounting/api-v-1-accounting-transactions-transaction-id-put';
import { ApiV1AccountingTransactionsTransactionIdPut$Params } from '../fn/accounting/api-v-1-accounting-transactions-transaction-id-put';
import { Entry } from '../models/entry';
import { LedgerAccount } from '../models/ledger-account';
import { Posting } from '../models/posting';
import { Transaction } from '../models/transaction';

@Injectable({ providedIn: 'root' })
export class AccountingService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiV1AccountingLedgerAccountsGet()` */
  static readonly ApiV1AccountingLedgerAccountsGetPath = '/api/v1/accounting/ledger_accounts';

  /**
   * List all ledger accounts.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiV1AccountingLedgerAccountsGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiV1AccountingLedgerAccountsGet$Response(params?: ApiV1AccountingLedgerAccountsGet$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'data'?: Array<LedgerAccount>;
}>> {
    const obs = apiV1AccountingLedgerAccountsGet(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * List all ledger accounts.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiV1AccountingLedgerAccountsGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiV1AccountingLedgerAccountsGet(params?: ApiV1AccountingLedgerAccountsGet$Params, context?: HttpContext): Observable<{
'data'?: Array<LedgerAccount>;
}> {
    const resp = this.apiV1AccountingLedgerAccountsGet$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<{
'data'?: Array<LedgerAccount>;
}>): {
'data'?: Array<LedgerAccount>;
} => r.body)
    );
  }

  /** Path part for operation `apiV1AccountingPostingsGet()` */
  static readonly ApiV1AccountingPostingsGetPath = '/api/v1/accounting/postings';

  /**
   * List all postings.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiV1AccountingPostingsGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiV1AccountingPostingsGet$Response(params?: ApiV1AccountingPostingsGet$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'data'?: Array<Posting>;
}>> {
    const obs = apiV1AccountingPostingsGet(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * List all postings.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiV1AccountingPostingsGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiV1AccountingPostingsGet(params?: ApiV1AccountingPostingsGet$Params, context?: HttpContext): Observable<{
'data'?: Array<Posting>;
}> {
    const resp = this.apiV1AccountingPostingsGet$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<{
'data'?: Array<Posting>;
}>): {
'data'?: Array<Posting>;
} => r.body)
    );
  }

  /** Path part for operation `apiV1AccountingEntriesGet()` */
  static readonly ApiV1AccountingEntriesGetPath = '/api/v1/accounting/entries';

  /**
   * List all entriee.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiV1AccountingEntriesGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiV1AccountingEntriesGet$Response(params?: ApiV1AccountingEntriesGet$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'data'?: Array<Entry>;
}>> {
    const obs = apiV1AccountingEntriesGet(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * List all entriee.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiV1AccountingEntriesGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiV1AccountingEntriesGet(params?: ApiV1AccountingEntriesGet$Params, context?: HttpContext): Observable<{
'data'?: Array<Entry>;
}> {
    const resp = this.apiV1AccountingEntriesGet$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<{
'data'?: Array<Entry>;
}>): {
'data'?: Array<Entry>;
} => r.body)
    );
  }

  /** Path part for operation `apiV1AccountingTransactionsGet()` */
  static readonly ApiV1AccountingTransactionsGetPath = '/api/v1/accounting/transactions';

  /**
   * List all transactions.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiV1AccountingTransactionsGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiV1AccountingTransactionsGet$Response(params?: ApiV1AccountingTransactionsGet$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'data'?: Array<Transaction>;
}>> {
    const obs = apiV1AccountingTransactionsGet(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * List all transactions.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiV1AccountingTransactionsGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiV1AccountingTransactionsGet(params?: ApiV1AccountingTransactionsGet$Params, context?: HttpContext): Observable<{
'data'?: Array<Transaction>;
}> {
    const resp = this.apiV1AccountingTransactionsGet$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<{
'data'?: Array<Transaction>;
}>): {
'data'?: Array<Transaction>;
} => r.body)
    );
  }

  /** Path part for operation `apiV1AccountingTransactionsPost()` */
  static readonly ApiV1AccountingTransactionsPostPath = '/api/v1/accounting/transactions';

  /**
   * Create transaction.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiV1AccountingTransactionsPost()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiV1AccountingTransactionsPost$Response(params?: ApiV1AccountingTransactionsPost$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    const obs = apiV1AccountingTransactionsPost(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Create transaction.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiV1AccountingTransactionsPost$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiV1AccountingTransactionsPost(params?: ApiV1AccountingTransactionsPost$Params, context?: HttpContext): Observable<void> {
    const resp = this.apiV1AccountingTransactionsPost$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `apiV1AccountingTransactionsTransactionIdPut()` */
  static readonly ApiV1AccountingTransactionsTransactionIdPutPath = '/api/v1/accounting/transactions/{transaction_id}';

  /**
   * Update or finalize a generated transaction.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiV1AccountingTransactionsTransactionIdPut()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  apiV1AccountingTransactionsTransactionIdPut$Response(params: ApiV1AccountingTransactionsTransactionIdPut$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    const obs = apiV1AccountingTransactionsTransactionIdPut(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Update or finalize a generated transaction.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiV1AccountingTransactionsTransactionIdPut$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  apiV1AccountingTransactionsTransactionIdPut(params: ApiV1AccountingTransactionsTransactionIdPut$Params, context?: HttpContext): Observable<void> {
    const resp = this.apiV1AccountingTransactionsTransactionIdPut$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `apiV1AccountingAccountsInfoGet()` */
  static readonly ApiV1AccountingAccountsInfoGetPath = '/api/v1/accounting/accounts/info';

  /**
   * Balance and health check.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiV1AccountingAccountsInfoGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiV1AccountingAccountsInfoGet$Response(params?: ApiV1AccountingAccountsInfoGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<AccountStatus>>> {
    const obs = apiV1AccountingAccountsInfoGet(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Balance and health check.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiV1AccountingAccountsInfoGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiV1AccountingAccountsInfoGet(params?: ApiV1AccountingAccountsInfoGet$Params, context?: HttpContext): Observable<Array<AccountStatus>> {
    const resp = this.apiV1AccountingAccountsInfoGet$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Array<AccountStatus>>): Array<AccountStatus> => r.body)
    );
  }

}
