/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { apiLivezGet } from '../fn/operations/api-livez-get';
import { ApiLivezGet$Params } from '../fn/operations/api-livez-get';
import { apiReadyzGet } from '../fn/operations/api-readyz-get';
import { ApiReadyzGet$Params } from '../fn/operations/api-readyz-get';

@Injectable({ providedIn: 'root' })
export class ApiService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiLivezGet()` */
  static readonly ApiLivezGetPath = '/api/livez';

  /**
   * liveness check - checks if process is deadlocked
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiLivezGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiLivezGet$Response(params?: ApiLivezGet$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'data'?: any;
}>> {
    const obs = apiLivezGet(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * liveness check - checks if process is deadlocked
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiLivezGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiLivezGet(params?: ApiLivezGet$Params, context?: HttpContext): Observable<{
'data'?: any;
}> {
    const resp = this.apiLivezGet$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<{
'data'?: any;
}>): {
'data'?: any;
} => r.body)
    );
  }

  /** Path part for operation `apiReadyzGet()` */
  static readonly ApiReadyzGetPath = '/api/readyz';

  /**
   * readiness check - checks if process can handle traffic (also considers downstream dependencies)
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiReadyzGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiReadyzGet$Response(params?: ApiReadyzGet$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'data'?: any;
}>> {
    const obs = apiReadyzGet(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * readiness check - checks if process can handle traffic (also considers downstream dependencies)
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiReadyzGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiReadyzGet(params?: ApiReadyzGet$Params, context?: HttpContext): Observable<{
'data'?: any;
}> {
    const resp = this.apiReadyzGet$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<{
'data'?: any;
}>): {
'data'?: any;
} => r.body)
    );
  }

}
