// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

// The atomic line items of a transaction. The sum of debits must equal the sum of credits for a given posting_id.
type Entry struct {
	// Primary key for the individual line item.
	ID int64 `json:"id"`
	// Specific line-item memo, if different from the main posting description.
	Description pgtype.Text `json:"description"`
	// Technical details specific to this leg of the transaction.
	SystemNotes pgtype.Text `json:"system_notes"`
	// Foreign key linking this entry to its parent transaction.
	PostingsID int64 `json:"postings_id"`
	// The specific account from the COA (chart of accounts; ledger_accounts table) being impacted.
	LedgerAccountsID int64 `json:"ledger_accounts_id"`
	// The value increase/decrease (base integer) on the debit side. 1 SGD = 1,000,000 mSGD
	DebitMicrosgd int64 `json:"debit_microsgd"`
	// The value increase/decrease (base integer) on the credit side. 1 SGD = 1,000,000 mSGD
	CreditMicrosgd int64 `json:"credit_microsgd"`
}

// The Chart of Accounts (COA). Defines the categories where value is moved.
type LedgerAccount struct {
	// Primary key for the account.
	ID int64 `json:"id"`
	// The human-friendly name of the account (e.g., Cash at Bank, Accounts Payable).
	Name string `json:"name"`
	// Detailed definition of what should be recorded in this account.
	Description pgtype.Text `json:"description"`
	// Self-reference to create an account hierarchy (e.g., Assets > Current Assets).
	ParentID pgtype.Int8 `json:"parent_id"`
}

// The Header/Journal Entry level. Groups multiple entries into a single balanced transaction.
type Posting struct {
	// Primary key for the transaction group.
	ID int64 `json:"id"`
	// The narrative description of the transaction for human review.
	Description pgtype.Text `json:"description"`
	// Technical metadata, source system IDs, or debugging info (e.g., source: asdf.csv).
	SystemNotes pgtype.Text `json:"system_notes"`
	// The effective date and time the financial event occurred.
	TransactedAt time.Time `json:"transacted_at"`
}
