/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TransactionEntry } from '../../models/transaction-entry';

export interface ApiV1AccountingTransactionsTransactionIdPut$Params {
  transaction_id: string;
      body?: {
'date': string;
'description': string;
'entries': Array<TransactionEntry>;
}
}

export function apiV1AccountingTransactionsTransactionIdPut(http: HttpClient, rootUrl: string, params: ApiV1AccountingTransactionsTransactionIdPut$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, apiV1AccountingTransactionsTransactionIdPut.PATH, 'put');
  if (params) {
    rb.path('transaction_id', params.transaction_id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

apiV1AccountingTransactionsTransactionIdPut.PATH = '/api/v1/accounting/transactions/{transaction_id}';
