/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AccountStatus } from '../../models/account-status';

export interface ApiV1AccountingAccountsInfoGet$Params {
}

export function apiV1AccountingAccountsInfoGet(http: HttpClient, rootUrl: string, params?: ApiV1AccountingAccountsInfoGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<AccountStatus>>> {
  const rb = new RequestBuilder(rootUrl, apiV1AccountingAccountsInfoGet.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<AccountStatus>>;
    })
  );
}

apiV1AccountingAccountsInfoGet.PATH = '/api/v1/accounting/accounts/info';
