/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Entry } from '../../models/entry';

export interface ApiV1AccountingEntriesGet$Params {
}

export function apiV1AccountingEntriesGet(http: HttpClient, rootUrl: string, params?: ApiV1AccountingEntriesGet$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'data'?: Array<Entry>;
}>> {
  const rb = new RequestBuilder(rootUrl, apiV1AccountingEntriesGet.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      'data'?: Array<Entry>;
      }>;
    })
  );
}

apiV1AccountingEntriesGet.PATH = '/api/v1/accounting/entries';
