/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Posting } from '../../models/posting';

export interface ApiV1AccountingPostingsGet$Params {
}

export function apiV1AccountingPostingsGet(http: HttpClient, rootUrl: string, params?: ApiV1AccountingPostingsGet$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'data'?: Array<Posting>;
}>> {
  const rb = new RequestBuilder(rootUrl, apiV1AccountingPostingsGet.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      'data'?: Array<Posting>;
      }>;
    })
  );
}

apiV1AccountingPostingsGet.PATH = '/api/v1/accounting/postings';
