/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Transaction } from '../../models/transaction';

export interface ApiV1AccountingTransactionsGet$Params {

/**
 * Filter transactions from this date (inclusive). Format: YYYY-MM-DD
 */
  start_date?: string;

/**
 * Filter transactions until this date (inclusive). Format: YYYY-MM-DD
 */
  end_date?: string;
}

export function apiV1AccountingTransactionsGet(http: HttpClient, rootUrl: string, params?: ApiV1AccountingTransactionsGet$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'data'?: Array<Transaction>;
}>> {
  const rb = new RequestBuilder(rootUrl, apiV1AccountingTransactionsGet.PATH, 'get');
  if (params) {
    rb.query('start_date', params.start_date, {});
    rb.query('end_date', params.end_date, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      'data'?: Array<Transaction>;
      }>;
    })
  );
}

apiV1AccountingTransactionsGet.PATH = '/api/v1/accounting/transactions';
