/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { LedgerAccount } from '../../models/ledger-account';

export interface ApiV1AccountingLedgerAccountsGet$Params {
}

export function apiV1AccountingLedgerAccountsGet(http: HttpClient, rootUrl: string, params?: ApiV1AccountingLedgerAccountsGet$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'data'?: Array<LedgerAccount>;
}>> {
  const rb = new RequestBuilder(rootUrl, apiV1AccountingLedgerAccountsGet.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      'data'?: Array<LedgerAccount>;
      }>;
    })
  );
}

apiV1AccountingLedgerAccountsGet.PATH = '/api/v1/accounting/ledger_accounts';
