/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Entry } from '../../models/entry';

export interface CreateEntry$Params {
  
    /**
     * create entry
     */
    body: {
'description': string;
'system_notes': string;
'ledger_accounts_id': string;
'postings_id': string;
'debit_amount': string;
'credit_amount': string;
}
}

export function createEntry(http: HttpClient, rootUrl: string, params: CreateEntry$Params, context?: HttpContext): Observable<StrictHttpResponse<Entry>> {
  const rb = new RequestBuilder(rootUrl, createEntry.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Entry>;
    })
  );
}

createEntry.PATH = '/api/v1/accounting/entries';
