/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AccountBalanceNode } from '../../models/account-balance-node';

export interface GetAccountBalances$Params {
  start_date: string;
  end_date: string;
}

export function getAccountBalances(http: HttpClient, rootUrl: string, params: GetAccountBalances$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'data'?: Array<AccountBalanceNode>;
}>> {
  const rb = new RequestBuilder(rootUrl, getAccountBalances.PATH, 'get');
  if (params) {
    rb.query('start_date', params.start_date, {});
    rb.query('end_date', params.end_date, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      'data'?: Array<AccountBalanceNode>;
      }>;
    })
  );
}

getAccountBalances.PATH = '/api/v1/accounting/reports/account_balances';
