/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Entry } from '../../models/entry';

export interface GetEntries$Params {
}

export function getEntries(http: HttpClient, rootUrl: string, params?: GetEntries$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'data'?: Array<Entry>;
}>> {
  const rb = new RequestBuilder(rootUrl, getEntries.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      'data'?: Array<Entry>;
      }>;
    })
  );
}

getEntries.PATH = '/api/v1/accounting/entries';
