/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Entry } from '../../models/entry';

export interface UpdateAccountingEntry$Params {
  entry_id: string;
  
    /**
     * replace entry object with new values
     */
    body?: Entry
}

export function updateAccountingEntry(http: HttpClient, rootUrl: string, params: UpdateAccountingEntry$Params, context?: HttpContext): Observable<StrictHttpResponse<{
}>> {
  const rb = new RequestBuilder(rootUrl, updateAccountingEntry.PATH, 'put');
  if (params) {
    rb.path('entry_id', params.entry_id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      }>;
    })
  );
}

updateAccountingEntry.PATH = '/api/v1/accounting/entries/{entry_id}';
