// Package webapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package webapi

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// AccountBalanceNode defines model for AccountBalanceNode.
type AccountBalanceNode struct {
	Credit          string  `json:"credit"`
	Debit           string  `json:"debit"`
	LedgerAccountId string  `json:"ledger_account_id"`
	Name            string  `json:"name"`
	ParentId        *string `json:"parent_id"`
	TotalCredit     string  `json:"total_credit"`
	TotalDebit      string  `json:"total_debit"`
}

// Entry Double-entry accounting ledger entry
type Entry struct {
	CreditAmount     string `json:"credit_amount"`
	DebitAmount      string `json:"debit_amount"`
	Description      string `json:"description"`
	Id               string `json:"id"`
	LedgerAccountsId string `json:"ledger_accounts_id"`
	PostingsId       string `json:"postings_id"`
	SystemNotes      string `json:"system_notes"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Detail A human-readable explanation specific to this occurence.
	Detail *string `json:"detail,omitempty"`

	// Instance A URI reference for this specific occurence (e.g. trace ID)
	Instance *string `json:"instance,omitempty"`

	// Status The HTTP status code generated for this occurrence.
	Status string `json:"status"`

	// Title A short, human-readable summary of the problem
	Title string `json:"title"`

	// Type A URI reference that identifies the problem type.
	Type string `json:"type"`
}

// LedgerAccount Double-entry accounting charter of accounts
type LedgerAccount struct {
	Description   string  `json:"description"`
	Id            string  `json:"id"`
	Name          string  `json:"name"`
	ParentId      *string `json:"parent_id"`
	QualifiedName string  `json:"qualified_name"`
}

// Posting Double-entry accounting ledger posting (journal entry)
type Posting struct {
	Description  string             `json:"description"`
	Id           string             `json:"id"`
	SystemNotes  string             `json:"system_notes"`
	TransactedAt openapi_types.Date `json:"transacted_at"`
}

// CreateEntryJSONBody defines parameters for CreateEntry.
type CreateEntryJSONBody struct {
	CreditAmount     string `json:"credit_amount"`
	DebitAmount      string `json:"debit_amount"`
	Description      string `json:"description"`
	LedgerAccountsId string `json:"ledger_accounts_id"`
	PostingsId       string `json:"postings_id"`
	SystemNotes      string `json:"system_notes"`
}

// GetAccountBalancesParams defines parameters for GetAccountBalances.
type GetAccountBalancesParams struct {
	StartDate openapi_types.Date `form:"start_date" json:"start_date"`
	EndDate   openapi_types.Date `form:"end_date" json:"end_date"`
}

// CreateEntryJSONRequestBody defines body for CreateEntry for application/json ContentType.
type CreateEntryJSONRequestBody CreateEntryJSONBody

// UpdateEntryJSONRequestBody defines body for UpdateEntry for application/json ContentType.
type UpdateEntryJSONRequestBody = Entry

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /api/livez)
	GetApiLivez(w http.ResponseWriter, r *http.Request)

	// (GET /api/readyz)
	GetApiReadyz(w http.ResponseWriter, r *http.Request)
	// List all entries
	// (GET /api/v1/accounting/entries)
	GetEntries(w http.ResponseWriter, r *http.Request)
	// create entry
	// (POST /api/v1/accounting/entries)
	CreateEntry(w http.ResponseWriter, r *http.Request)
	// delete ledger entry
	// (DELETE /api/v1/accounting/entries/{entry_id})
	DeleteEntry(w http.ResponseWriter, r *http.Request, entryId string)
	// replace of a ledger entry
	// (PUT /api/v1/accounting/entries/{entry_id})
	UpdateEntry(w http.ResponseWriter, r *http.Request, entryId string)
	// List all ledger accounts
	// (GET /api/v1/accounting/ledger_accounts)
	GetApiV1AccountingLedgerAccounts(w http.ResponseWriter, r *http.Request)
	// List all postings
	// (GET /api/v1/accounting/postings)
	GetApiV1AccountingPostings(w http.ResponseWriter, r *http.Request)
	// Get account balances and tree roll-ups for a date range
	// (GET /api/v1/accounting/reports/account_balances)
	GetAccountBalances(w http.ResponseWriter, r *http.Request, params GetAccountBalancesParams)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// (GET /api/livez)
func (_ Unimplemented) GetApiLivez(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /api/readyz)
func (_ Unimplemented) GetApiReadyz(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List all entries
// (GET /api/v1/accounting/entries)
func (_ Unimplemented) GetEntries(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// create entry
// (POST /api/v1/accounting/entries)
func (_ Unimplemented) CreateEntry(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// delete ledger entry
// (DELETE /api/v1/accounting/entries/{entry_id})
func (_ Unimplemented) DeleteEntry(w http.ResponseWriter, r *http.Request, entryId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// replace of a ledger entry
// (PUT /api/v1/accounting/entries/{entry_id})
func (_ Unimplemented) UpdateEntry(w http.ResponseWriter, r *http.Request, entryId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List all ledger accounts
// (GET /api/v1/accounting/ledger_accounts)
func (_ Unimplemented) GetApiV1AccountingLedgerAccounts(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List all postings
// (GET /api/v1/accounting/postings)
func (_ Unimplemented) GetApiV1AccountingPostings(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get account balances and tree roll-ups for a date range
// (GET /api/v1/accounting/reports/account_balances)
func (_ Unimplemented) GetAccountBalances(w http.ResponseWriter, r *http.Request, params GetAccountBalancesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetApiLivez operation middleware
func (siw *ServerInterfaceWrapper) GetApiLivez(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiLivez(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiReadyz operation middleware
func (siw *ServerInterfaceWrapper) GetApiReadyz(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiReadyz(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetEntries operation middleware
func (siw *ServerInterfaceWrapper) GetEntries(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetEntries(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateEntry operation middleware
func (siw *ServerInterfaceWrapper) CreateEntry(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateEntry(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteEntry operation middleware
func (siw *ServerInterfaceWrapper) DeleteEntry(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "entry_id" -------------
	var entryId string

	err = runtime.BindStyledParameterWithOptions("simple", "entry_id", chi.URLParam(r, "entry_id"), &entryId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "entry_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteEntry(w, r, entryId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateEntry operation middleware
func (siw *ServerInterfaceWrapper) UpdateEntry(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "entry_id" -------------
	var entryId string

	err = runtime.BindStyledParameterWithOptions("simple", "entry_id", chi.URLParam(r, "entry_id"), &entryId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "entry_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateEntry(w, r, entryId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiV1AccountingLedgerAccounts operation middleware
func (siw *ServerInterfaceWrapper) GetApiV1AccountingLedgerAccounts(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiV1AccountingLedgerAccounts(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiV1AccountingPostings operation middleware
func (siw *ServerInterfaceWrapper) GetApiV1AccountingPostings(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiV1AccountingPostings(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAccountBalances operation middleware
func (siw *ServerInterfaceWrapper) GetAccountBalances(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetAccountBalancesParams

	// ------------- Required query parameter "start_date" -------------

	if paramValue := r.URL.Query().Get("start_date"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "start_date"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "start_date", r.URL.Query(), &params.StartDate)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "start_date", Err: err})
		return
	}

	// ------------- Required query parameter "end_date" -------------

	if paramValue := r.URL.Query().Get("end_date"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "end_date"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "end_date", r.URL.Query(), &params.EndDate)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "end_date", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAccountBalances(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/livez", wrapper.GetApiLivez)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/readyz", wrapper.GetApiReadyz)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/accounting/entries", wrapper.GetEntries)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/accounting/entries", wrapper.CreateEntry)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api/v1/accounting/entries/{entry_id}", wrapper.DeleteEntry)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/api/v1/accounting/entries/{entry_id}", wrapper.UpdateEntry)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/accounting/ledger_accounts", wrapper.GetApiV1AccountingLedgerAccounts)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/accounting/postings", wrapper.GetApiV1AccountingPostings)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/accounting/reports/account_balances", wrapper.GetAccountBalances)
	})

	return r
}

type GetApiLivezRequestObject struct {
}

type GetApiLivezResponseObject interface {
	VisitGetApiLivezResponse(w http.ResponseWriter) error
}

type GetApiLivez200JSONResponse struct {
	Data interface{} `json:"data,omitempty"`
}

func (response GetApiLivez200JSONResponse) VisitGetApiLivezResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetApiReadyzRequestObject struct {
}

type GetApiReadyzResponseObject interface {
	VisitGetApiReadyzResponse(w http.ResponseWriter) error
}

type GetApiReadyz200JSONResponse struct {
	Data interface{} `json:"data,omitempty"`
}

func (response GetApiReadyz200JSONResponse) VisitGetApiReadyzResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetEntriesRequestObject struct {
}

type GetEntriesResponseObject interface {
	VisitGetEntriesResponse(w http.ResponseWriter) error
}

type GetEntries200JSONResponse struct {
	Data *[]Entry `json:"data,omitempty"`
}

func (response GetEntries200JSONResponse) VisitGetEntriesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetEntries500JSONResponse ErrorResponse

func (response GetEntries500JSONResponse) VisitGetEntriesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type CreateEntryRequestObject struct {
	Body *CreateEntryJSONRequestBody
}

type CreateEntryResponseObject interface {
	VisitCreateEntryResponse(w http.ResponseWriter) error
}

type CreateEntry201JSONResponse Entry

func (response CreateEntry201JSONResponse) VisitCreateEntryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateEntry400JSONResponse ErrorResponse

func (response CreateEntry400JSONResponse) VisitCreateEntryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateEntry500JSONResponse ErrorResponse

func (response CreateEntry500JSONResponse) VisitCreateEntryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type DeleteEntryRequestObject struct {
	EntryId string `json:"entry_id"`
}

type DeleteEntryResponseObject interface {
	VisitDeleteEntryResponse(w http.ResponseWriter) error
}

type DeleteEntry200JSONResponse map[string]interface{}

func (response DeleteEntry200JSONResponse) VisitDeleteEntryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type DeleteEntry400JSONResponse ErrorResponse

func (response DeleteEntry400JSONResponse) VisitDeleteEntryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type DeleteEntry404JSONResponse ErrorResponse

func (response DeleteEntry404JSONResponse) VisitDeleteEntryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type DeleteEntry500JSONResponse ErrorResponse

func (response DeleteEntry500JSONResponse) VisitDeleteEntryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type UpdateEntryRequestObject struct {
	EntryId string `json:"entry_id"`
	Body    *UpdateEntryJSONRequestBody
}

type UpdateEntryResponseObject interface {
	VisitUpdateEntryResponse(w http.ResponseWriter) error
}

type UpdateEntry200JSONResponse map[string]interface{}

func (response UpdateEntry200JSONResponse) VisitUpdateEntryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type UpdateEntry400JSONResponse ErrorResponse

func (response UpdateEntry400JSONResponse) VisitUpdateEntryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type UpdateEntry404JSONResponse ErrorResponse

func (response UpdateEntry404JSONResponse) VisitUpdateEntryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type UpdateEntry500JSONResponse ErrorResponse

func (response UpdateEntry500JSONResponse) VisitUpdateEntryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetApiV1AccountingLedgerAccountsRequestObject struct {
}

type GetApiV1AccountingLedgerAccountsResponseObject interface {
	VisitGetApiV1AccountingLedgerAccountsResponse(w http.ResponseWriter) error
}

type GetApiV1AccountingLedgerAccounts200JSONResponse struct {
	Data *[]LedgerAccount `json:"data,omitempty"`
}

func (response GetApiV1AccountingLedgerAccounts200JSONResponse) VisitGetApiV1AccountingLedgerAccountsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetApiV1AccountingPostingsRequestObject struct {
}

type GetApiV1AccountingPostingsResponseObject interface {
	VisitGetApiV1AccountingPostingsResponse(w http.ResponseWriter) error
}

type GetApiV1AccountingPostings200JSONResponse struct {
	Data *[]Posting `json:"data,omitempty"`
}

func (response GetApiV1AccountingPostings200JSONResponse) VisitGetApiV1AccountingPostingsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetAccountBalancesRequestObject struct {
	Params GetAccountBalancesParams
}

type GetAccountBalancesResponseObject interface {
	VisitGetAccountBalancesResponse(w http.ResponseWriter) error
}

type GetAccountBalances200JSONResponse struct {
	Data *[]AccountBalanceNode `json:"data,omitempty"`
}

func (response GetAccountBalances200JSONResponse) VisitGetAccountBalancesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetAccountBalances400JSONResponse ErrorResponse

func (response GetAccountBalances400JSONResponse) VisitGetAccountBalancesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetAccountBalances500JSONResponse ErrorResponse

func (response GetAccountBalances500JSONResponse) VisitGetAccountBalancesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {

	// (GET /api/livez)
	GetApiLivez(ctx context.Context, request GetApiLivezRequestObject) (GetApiLivezResponseObject, error)

	// (GET /api/readyz)
	GetApiReadyz(ctx context.Context, request GetApiReadyzRequestObject) (GetApiReadyzResponseObject, error)
	// List all entries
	// (GET /api/v1/accounting/entries)
	GetEntries(ctx context.Context, request GetEntriesRequestObject) (GetEntriesResponseObject, error)
	// create entry
	// (POST /api/v1/accounting/entries)
	CreateEntry(ctx context.Context, request CreateEntryRequestObject) (CreateEntryResponseObject, error)
	// delete ledger entry
	// (DELETE /api/v1/accounting/entries/{entry_id})
	DeleteEntry(ctx context.Context, request DeleteEntryRequestObject) (DeleteEntryResponseObject, error)
	// replace of a ledger entry
	// (PUT /api/v1/accounting/entries/{entry_id})
	UpdateEntry(ctx context.Context, request UpdateEntryRequestObject) (UpdateEntryResponseObject, error)
	// List all ledger accounts
	// (GET /api/v1/accounting/ledger_accounts)
	GetApiV1AccountingLedgerAccounts(ctx context.Context, request GetApiV1AccountingLedgerAccountsRequestObject) (GetApiV1AccountingLedgerAccountsResponseObject, error)
	// List all postings
	// (GET /api/v1/accounting/postings)
	GetApiV1AccountingPostings(ctx context.Context, request GetApiV1AccountingPostingsRequestObject) (GetApiV1AccountingPostingsResponseObject, error)
	// Get account balances and tree roll-ups for a date range
	// (GET /api/v1/accounting/reports/account_balances)
	GetAccountBalances(ctx context.Context, request GetAccountBalancesRequestObject) (GetAccountBalancesResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetApiLivez operation middleware
func (sh *strictHandler) GetApiLivez(w http.ResponseWriter, r *http.Request) {
	var request GetApiLivezRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetApiLivez(ctx, request.(GetApiLivezRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetApiLivez")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetApiLivezResponseObject); ok {
		if err := validResponse.VisitGetApiLivezResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetApiReadyz operation middleware
func (sh *strictHandler) GetApiReadyz(w http.ResponseWriter, r *http.Request) {
	var request GetApiReadyzRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetApiReadyz(ctx, request.(GetApiReadyzRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetApiReadyz")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetApiReadyzResponseObject); ok {
		if err := validResponse.VisitGetApiReadyzResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetEntries operation middleware
func (sh *strictHandler) GetEntries(w http.ResponseWriter, r *http.Request) {
	var request GetEntriesRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetEntries(ctx, request.(GetEntriesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetEntries")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetEntriesResponseObject); ok {
		if err := validResponse.VisitGetEntriesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateEntry operation middleware
func (sh *strictHandler) CreateEntry(w http.ResponseWriter, r *http.Request) {
	var request CreateEntryRequestObject

	var body CreateEntryJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateEntry(ctx, request.(CreateEntryRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateEntry")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateEntryResponseObject); ok {
		if err := validResponse.VisitCreateEntryResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteEntry operation middleware
func (sh *strictHandler) DeleteEntry(w http.ResponseWriter, r *http.Request, entryId string) {
	var request DeleteEntryRequestObject

	request.EntryId = entryId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteEntry(ctx, request.(DeleteEntryRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteEntry")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteEntryResponseObject); ok {
		if err := validResponse.VisitDeleteEntryResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateEntry operation middleware
func (sh *strictHandler) UpdateEntry(w http.ResponseWriter, r *http.Request, entryId string) {
	var request UpdateEntryRequestObject

	request.EntryId = entryId

	var body UpdateEntryJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateEntry(ctx, request.(UpdateEntryRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateEntry")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateEntryResponseObject); ok {
		if err := validResponse.VisitUpdateEntryResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetApiV1AccountingLedgerAccounts operation middleware
func (sh *strictHandler) GetApiV1AccountingLedgerAccounts(w http.ResponseWriter, r *http.Request) {
	var request GetApiV1AccountingLedgerAccountsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetApiV1AccountingLedgerAccounts(ctx, request.(GetApiV1AccountingLedgerAccountsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetApiV1AccountingLedgerAccounts")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetApiV1AccountingLedgerAccountsResponseObject); ok {
		if err := validResponse.VisitGetApiV1AccountingLedgerAccountsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetApiV1AccountingPostings operation middleware
func (sh *strictHandler) GetApiV1AccountingPostings(w http.ResponseWriter, r *http.Request) {
	var request GetApiV1AccountingPostingsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetApiV1AccountingPostings(ctx, request.(GetApiV1AccountingPostingsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetApiV1AccountingPostings")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetApiV1AccountingPostingsResponseObject); ok {
		if err := validResponse.VisitGetApiV1AccountingPostingsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetAccountBalances operation middleware
func (sh *strictHandler) GetAccountBalances(w http.ResponseWriter, r *http.Request, params GetAccountBalancesParams) {
	var request GetAccountBalancesRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetAccountBalances(ctx, request.(GetAccountBalancesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAccountBalances")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetAccountBalancesResponseObject); ok {
		if err := validResponse.VisitGetAccountBalancesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
