// Package webapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package webapi

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// AccountStatus defines model for AccountStatus.
type AccountStatus struct {
	AccountId   *openapi_types.UUID `json:"account_id,omitempty"`
	AccountName *string             `json:"account_name,omitempty"`
	Balance     *int                `json:"balance,omitempty"`

	// IsBalanced False if the sum of all transaction legs for this account is inconsistent
	IsBalanced *bool     `json:"is_balanced,omitempty"`
	Warnings   *[]string `json:"warnings,omitempty"`
}

// Entry Double-entry accounting entry - debit / credit
type Entry struct {
	// CreditAmount ...
	CreditAmount string `json:"credit_amount"`

	// DebitAmount ...
	DebitAmount string `json:"debit_amount"`

	// TransactionId transaction id
	TransactionId string `json:"transaction_id"`
}

// Transaction Double-entry accounting transaction
type Transaction struct {
	Date        openapi_types.Date  `json:"date"`
	Description string              `json:"description"`
	Entries     []Entry             `json:"entries"`
	Id          *openapi_types.UUID `json:"id,omitempty"`
}

// GetApiV1AccountingTransactionsParams defines parameters for GetApiV1AccountingTransactions.
type GetApiV1AccountingTransactionsParams struct {
	// StartDate Filter transactions from this date (inclusive). Format: YYYY-MM-DD
	StartDate *openapi_types.Date `form:"start_date,omitempty" json:"start_date,omitempty"`

	// EndDate Filter transactions until this date (inclusive). Format: YYYY-MM-DD
	EndDate *openapi_types.Date `form:"end_date,omitempty" json:"end_date,omitempty"`
}

// PutApiV1AccountingTransactionsTransactionIdJSONBody defines parameters for PutApiV1AccountingTransactionsTransactionId.
type PutApiV1AccountingTransactionsTransactionIdJSONBody struct {
	Date        openapi_types.Date `json:"date"`
	Description string             `json:"description"`
	Entries     []Entry            `json:"entries"`
}

// PutApiV1AccountingTransactionsTransactionIdJSONRequestBody defines body for PutApiV1AccountingTransactionsTransactionId for application/json ContentType.
type PutApiV1AccountingTransactionsTransactionIdJSONRequestBody PutApiV1AccountingTransactionsTransactionIdJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Balance and health check
	// (GET /api/v1/accounting/accounts/info)
	GetApiV1AccountingAccountsInfo(w http.ResponseWriter, r *http.Request)
	// List all transactions
	// (GET /api/v1/accounting/transactions)
	GetApiV1AccountingTransactions(w http.ResponseWriter, r *http.Request, params GetApiV1AccountingTransactionsParams)
	// Create transaction
	// (POST /api/v1/accounting/transactions)
	PostApiV1AccountingTransactions(w http.ResponseWriter, r *http.Request)
	// Update or finalize a generated transaction
	// (PUT /api/v1/accounting/transactions/{transaction_id})
	PutApiV1AccountingTransactionsTransactionId(w http.ResponseWriter, r *http.Request, transactionId openapi_types.UUID)

	// (GET /livez)
	GetLivez(w http.ResponseWriter, r *http.Request)

	// (GET /readyz)
	GetReadyz(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Balance and health check
// (GET /api/v1/accounting/accounts/info)
func (_ Unimplemented) GetApiV1AccountingAccountsInfo(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List all transactions
// (GET /api/v1/accounting/transactions)
func (_ Unimplemented) GetApiV1AccountingTransactions(w http.ResponseWriter, r *http.Request, params GetApiV1AccountingTransactionsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create transaction
// (POST /api/v1/accounting/transactions)
func (_ Unimplemented) PostApiV1AccountingTransactions(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update or finalize a generated transaction
// (PUT /api/v1/accounting/transactions/{transaction_id})
func (_ Unimplemented) PutApiV1AccountingTransactionsTransactionId(w http.ResponseWriter, r *http.Request, transactionId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /livez)
func (_ Unimplemented) GetLivez(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /readyz)
func (_ Unimplemented) GetReadyz(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetApiV1AccountingAccountsInfo operation middleware
func (siw *ServerInterfaceWrapper) GetApiV1AccountingAccountsInfo(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiV1AccountingAccountsInfo(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiV1AccountingTransactions operation middleware
func (siw *ServerInterfaceWrapper) GetApiV1AccountingTransactions(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetApiV1AccountingTransactionsParams

	// ------------- Optional query parameter "start_date" -------------

	err = runtime.BindQueryParameter("form", true, false, "start_date", r.URL.Query(), &params.StartDate)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "start_date", Err: err})
		return
	}

	// ------------- Optional query parameter "end_date" -------------

	err = runtime.BindQueryParameter("form", true, false, "end_date", r.URL.Query(), &params.EndDate)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "end_date", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiV1AccountingTransactions(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostApiV1AccountingTransactions operation middleware
func (siw *ServerInterfaceWrapper) PostApiV1AccountingTransactions(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostApiV1AccountingTransactions(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutApiV1AccountingTransactionsTransactionId operation middleware
func (siw *ServerInterfaceWrapper) PutApiV1AccountingTransactionsTransactionId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "transaction_id" -------------
	var transactionId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "transaction_id", chi.URLParam(r, "transaction_id"), &transactionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "transaction_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutApiV1AccountingTransactionsTransactionId(w, r, transactionId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetLivez operation middleware
func (siw *ServerInterfaceWrapper) GetLivez(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetLivez(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetReadyz operation middleware
func (siw *ServerInterfaceWrapper) GetReadyz(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetReadyz(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/accounting/accounts/info", wrapper.GetApiV1AccountingAccountsInfo)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/accounting/transactions", wrapper.GetApiV1AccountingTransactions)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/accounting/transactions", wrapper.PostApiV1AccountingTransactions)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/api/v1/accounting/transactions/{transaction_id}", wrapper.PutApiV1AccountingTransactionsTransactionId)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/livez", wrapper.GetLivez)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/readyz", wrapper.GetReadyz)
	})

	return r
}

type GetApiV1AccountingAccountsInfoRequestObject struct {
}

type GetApiV1AccountingAccountsInfoResponseObject interface {
	VisitGetApiV1AccountingAccountsInfoResponse(w http.ResponseWriter) error
}

type GetApiV1AccountingAccountsInfo200JSONResponse []AccountStatus

func (response GetApiV1AccountingAccountsInfo200JSONResponse) VisitGetApiV1AccountingAccountsInfoResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetApiV1AccountingTransactionsRequestObject struct {
	Params GetApiV1AccountingTransactionsParams
}

type GetApiV1AccountingTransactionsResponseObject interface {
	VisitGetApiV1AccountingTransactionsResponse(w http.ResponseWriter) error
}

type GetApiV1AccountingTransactions200JSONResponse struct {
	Data *[]Transaction `json:"data,omitempty"`
}

func (response GetApiV1AccountingTransactions200JSONResponse) VisitGetApiV1AccountingTransactionsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostApiV1AccountingTransactionsRequestObject struct {
}

type PostApiV1AccountingTransactionsResponseObject interface {
	VisitPostApiV1AccountingTransactionsResponse(w http.ResponseWriter) error
}

type PostApiV1AccountingTransactions201Response struct {
}

func (response PostApiV1AccountingTransactions201Response) VisitPostApiV1AccountingTransactionsResponse(w http.ResponseWriter) error {
	w.WriteHeader(201)
	return nil
}

type PutApiV1AccountingTransactionsTransactionIdRequestObject struct {
	TransactionId openapi_types.UUID `json:"transaction_id"`
	Body          *PutApiV1AccountingTransactionsTransactionIdJSONRequestBody
}

type PutApiV1AccountingTransactionsTransactionIdResponseObject interface {
	VisitPutApiV1AccountingTransactionsTransactionIdResponse(w http.ResponseWriter) error
}

type PutApiV1AccountingTransactionsTransactionId204Response struct {
}

func (response PutApiV1AccountingTransactionsTransactionId204Response) VisitPutApiV1AccountingTransactionsTransactionIdResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type GetLivezRequestObject struct {
}

type GetLivezResponseObject interface {
	VisitGetLivezResponse(w http.ResponseWriter) error
}

type GetLivez200JSONResponse struct {
	Data interface{} `json:"data,omitempty"`
}

func (response GetLivez200JSONResponse) VisitGetLivezResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetReadyzRequestObject struct {
}

type GetReadyzResponseObject interface {
	VisitGetReadyzResponse(w http.ResponseWriter) error
}

type GetReadyz200JSONResponse struct {
	Data interface{} `json:"data,omitempty"`
}

func (response GetReadyz200JSONResponse) VisitGetReadyzResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Balance and health check
	// (GET /api/v1/accounting/accounts/info)
	GetApiV1AccountingAccountsInfo(ctx context.Context, request GetApiV1AccountingAccountsInfoRequestObject) (GetApiV1AccountingAccountsInfoResponseObject, error)
	// List all transactions
	// (GET /api/v1/accounting/transactions)
	GetApiV1AccountingTransactions(ctx context.Context, request GetApiV1AccountingTransactionsRequestObject) (GetApiV1AccountingTransactionsResponseObject, error)
	// Create transaction
	// (POST /api/v1/accounting/transactions)
	PostApiV1AccountingTransactions(ctx context.Context, request PostApiV1AccountingTransactionsRequestObject) (PostApiV1AccountingTransactionsResponseObject, error)
	// Update or finalize a generated transaction
	// (PUT /api/v1/accounting/transactions/{transaction_id})
	PutApiV1AccountingTransactionsTransactionId(ctx context.Context, request PutApiV1AccountingTransactionsTransactionIdRequestObject) (PutApiV1AccountingTransactionsTransactionIdResponseObject, error)

	// (GET /livez)
	GetLivez(ctx context.Context, request GetLivezRequestObject) (GetLivezResponseObject, error)

	// (GET /readyz)
	GetReadyz(ctx context.Context, request GetReadyzRequestObject) (GetReadyzResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetApiV1AccountingAccountsInfo operation middleware
func (sh *strictHandler) GetApiV1AccountingAccountsInfo(w http.ResponseWriter, r *http.Request) {
	var request GetApiV1AccountingAccountsInfoRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetApiV1AccountingAccountsInfo(ctx, request.(GetApiV1AccountingAccountsInfoRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetApiV1AccountingAccountsInfo")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetApiV1AccountingAccountsInfoResponseObject); ok {
		if err := validResponse.VisitGetApiV1AccountingAccountsInfoResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetApiV1AccountingTransactions operation middleware
func (sh *strictHandler) GetApiV1AccountingTransactions(w http.ResponseWriter, r *http.Request, params GetApiV1AccountingTransactionsParams) {
	var request GetApiV1AccountingTransactionsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetApiV1AccountingTransactions(ctx, request.(GetApiV1AccountingTransactionsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetApiV1AccountingTransactions")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetApiV1AccountingTransactionsResponseObject); ok {
		if err := validResponse.VisitGetApiV1AccountingTransactionsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostApiV1AccountingTransactions operation middleware
func (sh *strictHandler) PostApiV1AccountingTransactions(w http.ResponseWriter, r *http.Request) {
	var request PostApiV1AccountingTransactionsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostApiV1AccountingTransactions(ctx, request.(PostApiV1AccountingTransactionsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostApiV1AccountingTransactions")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostApiV1AccountingTransactionsResponseObject); ok {
		if err := validResponse.VisitPostApiV1AccountingTransactionsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PutApiV1AccountingTransactionsTransactionId operation middleware
func (sh *strictHandler) PutApiV1AccountingTransactionsTransactionId(w http.ResponseWriter, r *http.Request, transactionId openapi_types.UUID) {
	var request PutApiV1AccountingTransactionsTransactionIdRequestObject

	request.TransactionId = transactionId

	var body PutApiV1AccountingTransactionsTransactionIdJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PutApiV1AccountingTransactionsTransactionId(ctx, request.(PutApiV1AccountingTransactionsTransactionIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PutApiV1AccountingTransactionsTransactionId")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PutApiV1AccountingTransactionsTransactionIdResponseObject); ok {
		if err := validResponse.VisitPutApiV1AccountingTransactionsTransactionIdResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetLivez operation middleware
func (sh *strictHandler) GetLivez(w http.ResponseWriter, r *http.Request) {
	var request GetLivezRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetLivez(ctx, request.(GetLivezRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetLivez")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetLivezResponseObject); ok {
		if err := validResponse.VisitGetLivezResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetReadyz operation middleware
func (sh *strictHandler) GetReadyz(w http.ResponseWriter, r *http.Request) {
	var request GetReadyzRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetReadyz(ctx, request.(GetReadyzRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetReadyz")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetReadyzResponseObject); ok {
		if err := validResponse.VisitGetReadyzResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
